services:
  - type: web
    name: tienda-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
      python manage.py shell < tienda_backend/create_superuser.py
    startCommand: gunicorn tienda_backend.wsgi:application
    envVars:
      - key: DATABASE_URL
        value: "postgres://usuario:password@host:puerto/nombre_db"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DJANGO_SUPERUSER_USERNAME
        value: "admin"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "admin@example.com"
      - key: DJANGO_SUPERUSER_PASSWORD
        value: "admin123"
